import { ChangeDetectionStrategy, Component } from '@angular/core';
import type { MenuItem } from '@wawjs/ngx-prime/api';
import { PanelMenuModule } from '@wawjs/ngx-prime/panelmenu';

@Component({
	selector: 'uk-sidebar',
	imports: [PanelMenuModule],
	templateUrl: './uikit-sidebar.html',
	styleUrl: './uikit-sidebar.scss',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UikitSidebar {
	protected readonly items: MenuItem[] = [
		{
			label: 'Form',
			icon: 'pi pi-file-edit',
			items: [
				{ label: 'Input', routerLink: ['/form/input'] },
				{ label: 'Select', routerLink: ['/form/select'] },
				{ label: 'Checkbox', routerLink: ['/form/checkbox'] },
				{ label: 'RadioButton', routerLink: ['/form/radiobutton'] },
				{ label: 'Rating', routerLink: ['/form/rating'] },
				{ label: 'Slider', routerLink: ['/form/slider'] },
				{ label: 'Textarea', routerLink: ['/form/textarea'] },
				{ label: 'ToggleButton', routerLink: ['/form/togglebutton'] },
				{ label: 'ToggleSwitch', routerLink: ['/form/toggleswitch'] },
				{ label: 'FloatLabel', routerLink: ['/form/floatlabel'] },
				{ label: 'InputNumber', routerLink: ['/form/inputnumber'] },
				{ label: 'Password', routerLink: ['/form/password'] },
				{ label: 'SelectButton', routerLink: ['/form/selectbutton'] },
				{ label: 'AutoComplete', routerLink: ['/form/autocomplete'] },
				{ label: 'CascadeSelect', routerLink: ['/form/cascadeselect'] },
				{ label: 'ColorPicker', routerLink: ['/form/colorpicker'] },
				{ label: 'DatePicker', routerLink: ['/form/datepicker'] },
				{ label: 'Editor', routerLink: ['/form/editor'] },
				{ label: 'Fieldset', routerLink: ['/form/fieldset'] },
				{ label: 'IconField', routerLink: ['/form/iconfield'] },
				{ label: 'InputGroup', routerLink: ['/form/inputgroup'] },
				{ label: 'InputMask', routerLink: ['/form/inputmask'] },
				{ label: 'InputOtp', routerLink: ['/form/inputotp'] },
				{ label: 'KeyFilter', routerLink: ['/form/keyfilter'] },
				{ label: 'Listbox', routerLink: ['/form/listbox'] },
				{ label: 'MultiSelect', routerLink: ['/form/multiselect'] },
				{ label: 'TreeSelect', routerLink: ['/form/treeselect'] },
				{ label: 'FileUpload', routerLink: ['/form/fileupload'] },
				{ label: 'Form Layout', routerLink: ['/form/form-layout'] },
				{ label: 'File', routerLink: ['/form/file-composite'] },
			],
		},
		{
			label: 'Button',
			icon: 'pi pi-stop',
			items: [
				{ label: 'Button', routerLink: ['/button/button'] },
				{ label: 'ButtonGroup', routerLink: ['/button/buttongroup'] },
				{ label: 'SplitButton', routerLink: ['/button/splitbutton'] },
				{ label: 'SpeedDial', routerLink: ['/button/speeddial'] },
			],
		},
		{
			label: 'Data',
			icon: 'pi pi-table',
			items: [
				{ label: 'Table', routerLink: ['/data/table'] },
				{ label: 'DataView', routerLink: ['/data/dataview'] },
				{ label: 'OrderList', routerLink: ['/data/orderlist'] },
				{ label: 'OrganizationChart', routerLink: ['/data/organizationchart'] },
				{ label: 'Paginator', routerLink: ['/data/paginator'] },
				{ label: 'PickList', routerLink: ['/data/picklist'] },
				{ label: 'Timeline', routerLink: ['/data/timeline'] },
				{ label: 'Tree', routerLink: ['/data/tree'] },
				{ label: 'TreeTable', routerLink: ['/data/treetable'] },
				{ label: 'List', routerLink: ['/data/list-composite'] },
				{ label: 'Tree (Composite)', routerLink: ['/data/tree-composite'] },
				{ label: 'Timeline (Composite)', routerLink: ['/data/timeline-composite'] },
			],
		},
		{
			label: 'Overlay',
			icon: 'pi pi-window-maximize',
			items: [
				{ label: 'Dialog', routerLink: ['/overlay/dialog'] },
				{ label: 'DynamicDialog', routerLink: ['/overlay/dynamicdialog'] },
				{ label: 'Drawer', routerLink: ['/overlay/drawer'] },
				{ label: 'Popover', routerLink: ['/overlay/popover'] },
				{ label: 'ConfirmDialog', routerLink: ['/overlay/confirmdialog'] },
				{ label: 'ConfirmPopup', routerLink: ['/overlay/confirmpopup'] },
				{ label: 'ContextMenu', routerLink: ['/overlay/contextmenu'] },
				{ label: 'Tooltip', routerLink: ['/overlay/tooltip'] },
				{ label: 'BlockUI', routerLink: ['/overlay/blockui'] },
			],
		},
		{
			label: 'Layout',
			icon: 'pi pi-th-large',
			items: [
				{ label: 'Card', routerLink: ['/layout/card'] },
				{ label: 'Accordion', routerLink: ['/layout/accordion'] },
				{ label: 'Divider', routerLink: ['/layout/divider'] },
				{ label: 'Panel', routerLink: ['/layout/panel'] },
				{ label: 'ScrollPanel', routerLink: ['/layout/scrollpanel'] },
				{ label: 'Splitter', routerLink: ['/layout/splitter'] },
				{ label: 'Toolbar', routerLink: ['/layout/toolbar'] },
				{ label: 'Inplace', routerLink: ['/layout/inplace'] },
				{ label: 'Panel (Composite)', routerLink: ['/layout/panel-composite'] },
			],
		},
		{
			label: 'Navigation',
			icon: 'pi pi-compass',
			items: [
				{ label: 'Breadcrumb', routerLink: ['/navigation/breadcrumb'] },
				{ label: 'Menu', routerLink: ['/navigation/menu'] },
				{ label: 'Menubar', routerLink: ['/navigation/menubar'] },
				{ label: 'MegaMenu', routerLink: ['/navigation/megamenu'] },
				{ label: 'PanelMenu', routerLink: ['/navigation/panelmenu'] },
				{ label: 'Steps', routerLink: ['/navigation/steps'] },
				{ label: 'Stepper', routerLink: ['/navigation/stepper'] },
				{ label: 'Tabs', routerLink: ['/navigation/tabs'] },
				{ label: 'TieredMenu', routerLink: ['/navigation/tieredmenu'] },
				{ label: 'Dock', routerLink: ['/navigation/dock'] },
				{ label: 'Menu in Context', routerLink: ['/navigation/menu-in-context'] },
			],
		},
		{
			label: 'Feedback',
			icon: 'pi pi-bell',
			items: [
				{ label: 'Message', routerLink: ['/feedback/message'] },
				{ label: 'Toast', routerLink: ['/feedback/toast'] },
				{ label: 'ProgressBar', routerLink: ['/feedback/progressbar'] },
				{ label: 'ProgressSpinner', routerLink: ['/feedback/progressspinner'] },
				{ label: 'Skeleton', routerLink: ['/feedback/skeleton'] },
				{ label: 'Badge', routerLink: ['/feedback/badge'] },
				{ label: 'Tag', routerLink: ['/feedback/tag'] },
				{ label: 'MeterGroup', routerLink: ['/feedback/metergroup'] },
				{ label: 'Message/Toast Stack', routerLink: ['/feedback/message-toast-stack'] },
			],
		},
		{
			label: 'Media',
			icon: 'pi pi-image',
			items: [
				{ label: 'Avatar', routerLink: ['/media/avatar'] },
				{ label: 'AvatarGroup', routerLink: ['/media/avatargroup'] },
				{ label: 'Carousel', routerLink: ['/media/carousel'] },
				{ label: 'Chart', routerLink: ['/media/chart'] },
				{ label: 'Galleria', routerLink: ['/media/galleria'] },
				{ label: 'Image', routerLink: ['/media/image'] },
				{ label: 'ImageCompare', routerLink: ['/media/imagecompare'] },
				{ label: 'Media Gallery', routerLink: ['/media/media-gallery'] },
				{ label: 'Chart Dashboard', routerLink: ['/media/chart-dashboard'] },
			],
		},
		{
			label: 'Misc',
			icon: 'pi pi-sparkles',
			items: [
				{ label: 'Chip', routerLink: ['/misc/chip'] },
				{ label: 'Knob', routerLink: ['/misc/knob'] },
				{ label: 'Terminal', routerLink: ['/misc/terminal'] },
				{ label: 'AnimateOnScroll', routerLink: ['/misc/animateonscroll'] },
			],
		},
	];
}
