import { ChangeDetectionStrategy, Component } from '@angular/core';
import type { MenuItem } from '@wawjs/ngx-prime/api';
import { PanelMenuModule } from '@wawjs/ngx-prime/panelmenu';

@Component({
	selector: 'sc-sidebar',
	imports: [PanelMenuModule],
	templateUrl: './showcase-sidebar.html',
	styleUrl: './showcase-sidebar.scss',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ShowcaseSidebar {
	protected readonly items: MenuItem[] = [
		{ label: 'Translator', icon: 'pi pi-language', routerLink: ['/translations'] },
		{
			label: 'UI Kit',
			icon: 'pi pi-palette',
			items: [
				{
					label: 'Form',
					items: [
						{ label: 'Input', routerLink: ['/uikit/form/input'] },
						{ label: 'Select', routerLink: ['/uikit/form/select'] },
						{ label: 'Checkbox', routerLink: ['/uikit/form/checkbox'] },
						{ label: 'RadioButton', routerLink: ['/uikit/form/radiobutton'] },
						{ label: 'Rating', routerLink: ['/uikit/form/rating'] },
						{ label: 'Slider', routerLink: ['/uikit/form/slider'] },
						{ label: 'Textarea', routerLink: ['/uikit/form/textarea'] },
						{ label: 'ToggleButton', routerLink: ['/uikit/form/togglebutton'] },
						{ label: 'ToggleSwitch', routerLink: ['/uikit/form/toggleswitch'] },
						{ label: 'FloatLabel', routerLink: ['/uikit/form/floatlabel'] },
						{ label: 'InputNumber', routerLink: ['/uikit/form/inputnumber'] },
						{ label: 'Password', routerLink: ['/uikit/form/password'] },
						{ label: 'SelectButton', routerLink: ['/uikit/form/selectbutton'] },
						{ label: 'AutoComplete', routerLink: ['/uikit/form/autocomplete'] },
						{ label: 'CascadeSelect', routerLink: ['/uikit/form/cascadeselect'] },
						{ label: 'ColorPicker', routerLink: ['/uikit/form/colorpicker'] },
						{ label: 'DatePicker', routerLink: ['/uikit/form/datepicker'] },
						{ label: 'Editor', routerLink: ['/uikit/form/editor'] },
						{ label: 'Fieldset', routerLink: ['/uikit/form/fieldset'] },
						{ label: 'IconField', routerLink: ['/uikit/form/iconfield'] },
						{ label: 'InputGroup', routerLink: ['/uikit/form/inputgroup'] },
						{ label: 'InputMask', routerLink: ['/uikit/form/inputmask'] },
						{ label: 'InputOtp', routerLink: ['/uikit/form/inputotp'] },
						{ label: 'KeyFilter', routerLink: ['/uikit/form/keyfilter'] },
						{ label: 'Listbox', routerLink: ['/uikit/form/listbox'] },
						{ label: 'MultiSelect', routerLink: ['/uikit/form/multiselect'] },
						{ label: 'TreeSelect', routerLink: ['/uikit/form/treeselect'] },
						{ label: 'FileUpload', routerLink: ['/uikit/form/fileupload'] },
						{ label: 'Form Layout', routerLink: ['/uikit/form/form-layout'] },
						{ label: 'File', routerLink: ['/uikit/form/file-composite'] },
					],
				},
				{
					label: 'Button',
					items: [
						{ label: 'Button', routerLink: ['/uikit/button/button'] },
						{ label: 'ButtonGroup', routerLink: ['/uikit/button/buttongroup'] },
						{ label: 'SplitButton', routerLink: ['/uikit/button/splitbutton'] },
						{ label: 'SpeedDial', routerLink: ['/uikit/button/speeddial'] },
					],
				},
				{
					label: 'Data',
					items: [
						{ label: 'Table', routerLink: ['/uikit/data/table'] },
						{ label: 'DataView', routerLink: ['/uikit/data/dataview'] },
						{ label: 'OrderList', routerLink: ['/uikit/data/orderlist'] },
						{ label: 'OrganizationChart', routerLink: ['/uikit/data/organizationchart'] },
						{ label: 'Paginator', routerLink: ['/uikit/data/paginator'] },
						{ label: 'PickList', routerLink: ['/uikit/data/picklist'] },
						{ label: 'Timeline', routerLink: ['/uikit/data/timeline'] },
						{ label: 'Tree', routerLink: ['/uikit/data/tree'] },
						{ label: 'TreeTable', routerLink: ['/uikit/data/treetable'] },
						{ label: 'List', routerLink: ['/uikit/data/list-composite'] },
						{ label: 'Tree (Composite)', routerLink: ['/uikit/data/tree-composite'] },
						{ label: 'Timeline (Composite)', routerLink: ['/uikit/data/timeline-composite'] },
					],
				},
				{
					label: 'Overlay',
					items: [
						{ label: 'Dialog', routerLink: ['/uikit/overlay/dialog'] },
						{ label: 'DynamicDialog', routerLink: ['/uikit/overlay/dynamicdialog'] },
						{ label: 'Drawer', routerLink: ['/uikit/overlay/drawer'] },
						{ label: 'Popover', routerLink: ['/uikit/overlay/popover'] },
						{ label: 'ConfirmDialog', routerLink: ['/uikit/overlay/confirmdialog'] },
						{ label: 'ConfirmPopup', routerLink: ['/uikit/overlay/confirmpopup'] },
						{ label: 'ContextMenu', routerLink: ['/uikit/overlay/contextmenu'] },
						{ label: 'Tooltip', routerLink: ['/uikit/overlay/tooltip'] },
						{ label: 'BlockUI', routerLink: ['/uikit/overlay/blockui'] },
					],
				},
				{
					label: 'Layout',
					items: [
						{ label: 'Card', routerLink: ['/uikit/layout/card'] },
						{ label: 'Accordion', routerLink: ['/uikit/layout/accordion'] },
						{ label: 'Divider', routerLink: ['/uikit/layout/divider'] },
						{ label: 'Panel', routerLink: ['/uikit/layout/panel'] },
						{ label: 'ScrollPanel', routerLink: ['/uikit/layout/scrollpanel'] },
						{ label: 'Splitter', routerLink: ['/uikit/layout/splitter'] },
						{ label: 'Toolbar', routerLink: ['/uikit/layout/toolbar'] },
						{ label: 'Inplace', routerLink: ['/uikit/layout/inplace'] },
						{ label: 'Panel (Composite)', routerLink: ['/uikit/layout/panel-composite'] },
					],
				},
				{
					label: 'Navigation',
					items: [
						{ label: 'Breadcrumb', routerLink: ['/uikit/navigation/breadcrumb'] },
						{ label: 'Menu', routerLink: ['/uikit/navigation/menu'] },
						{ label: 'Menubar', routerLink: ['/uikit/navigation/menubar'] },
						{ label: 'MegaMenu', routerLink: ['/uikit/navigation/megamenu'] },
						{ label: 'PanelMenu', routerLink: ['/uikit/navigation/panelmenu'] },
						{ label: 'Steps', routerLink: ['/uikit/navigation/steps'] },
						{ label: 'Stepper', routerLink: ['/uikit/navigation/stepper'] },
						{ label: 'Tabs', routerLink: ['/uikit/navigation/tabs'] },
						{ label: 'TieredMenu', routerLink: ['/uikit/navigation/tieredmenu'] },
						{ label: 'Dock', routerLink: ['/uikit/navigation/dock'] },
						{ label: 'Menu in Context', routerLink: ['/uikit/navigation/menu-in-context'] },
					],
				},
				{
					label: 'Feedback',
					items: [
						{ label: 'Message', routerLink: ['/uikit/feedback/message'] },
						{ label: 'Toast', routerLink: ['/uikit/feedback/toast'] },
						{ label: 'ProgressBar', routerLink: ['/uikit/feedback/progressbar'] },
						{ label: 'ProgressSpinner', routerLink: ['/uikit/feedback/progressspinner'] },
						{ label: 'Skeleton', routerLink: ['/uikit/feedback/skeleton'] },
						{ label: 'Badge', routerLink: ['/uikit/feedback/badge'] },
						{ label: 'Tag', routerLink: ['/uikit/feedback/tag'] },
						{ label: 'MeterGroup', routerLink: ['/uikit/feedback/metergroup'] },
						{ label: 'Message/Toast Stack', routerLink: ['/uikit/feedback/message-toast-stack'] },
					],
				},
				{
					label: 'Media',
					items: [
						{ label: 'Avatar', routerLink: ['/uikit/media/avatar'] },
						{ label: 'AvatarGroup', routerLink: ['/uikit/media/avatargroup'] },
						{ label: 'Carousel', routerLink: ['/uikit/media/carousel'] },
						{ label: 'Chart', routerLink: ['/uikit/media/chart'] },
						{ label: 'Galleria', routerLink: ['/uikit/media/galleria'] },
						{ label: 'Image', routerLink: ['/uikit/media/image'] },
						{ label: 'ImageCompare', routerLink: ['/uikit/media/imagecompare'] },
						{ label: 'Media Gallery', routerLink: ['/uikit/media/media-gallery'] },
						{ label: 'Chart Dashboard', routerLink: ['/uikit/media/chart-dashboard'] },
					],
				},
				{
					label: 'Misc',
					items: [
						{ label: 'Chip', routerLink: ['/uikit/misc/chip'] },
						{ label: 'Knob', routerLink: ['/uikit/misc/knob'] },
						{ label: 'Terminal', routerLink: ['/uikit/misc/terminal'] },
						{ label: 'AnimateOnScroll', routerLink: ['/uikit/misc/animateonscroll'] },
					],
				},
				{ label: 'Design Lab', routerLink: ['/uikit/design-lab'] },
			],
		},
		{
			label: 'Dashboards',
			icon: 'pi pi-home',
			items: [
				{ label: 'Default', routerLink: ['/dashboards/default'] },
				{ label: 'Analytics', routerLink: ['/dashboards/analytics'] },
			],
		},
		{
			label: 'Users',
			icon: 'pi pi-users',
			items: [
				{ label: 'List', routerLink: ['/users/list'] },
				{ label: 'Profile', routerLink: ['/users/profile'] },
				{ label: 'Create / Edit', routerLink: ['/users/create-edit'] },
			],
		},
		{
			label: 'Ecommerce',
			icon: 'pi pi-shopping-cart',
			items: [
				{ label: 'Products', routerLink: ['/ecommerce/products'] },
				{ label: 'Create / Edit Product', routerLink: ['/ecommerce/product-create-edit'] },
				{ label: 'Orders', routerLink: ['/ecommerce/orders'] },
				{ label: 'Order Details', routerLink: ['/ecommerce/order-details'] },
			],
		},
		{
			label: 'Projects',
			icon: 'pi pi-folder',
			items: [
				{ label: 'List', routerLink: ['/projects/list'] },
				{ label: 'Project Details', routerLink: ['/projects/project-details'] },
				{ label: 'Tasks', routerLink: ['/projects/tasks'] },
			],
		},
		{
			label: 'Applications',
			icon: 'pi pi-th-large',
			items: [
				{ label: 'Calendar', routerLink: ['/applications/calendar'] },
				{ label: 'Chat', routerLink: ['/applications/chat'] },
				{ label: 'Files', routerLink: ['/applications/files'] },
			],
		},
		{
			label: 'Account',
			icon: 'pi pi-cog',
			items: [{ label: 'Settings', routerLink: ['/account/settings'] }],
		},
	];
}
